#!/bin/bash
#
# cambiahostname: Script para cambiar el nombre de una máquina y realizar un pkgsync
#
# Funcionamiento:
# * Es posible introducir el nombre de la máquina como parámetro.
# * Si no se introduce el nombre como parámetro, tratará de obtenerlo consultando al DNS definido en DNSSERVER.
# * Si no se puede obtener el nombre consultando al servidor DNS, se solicita su introdución mediante teclado.
#
# Esteban M. Navas <algodelinux@gmail.com>
# Fecha creación:      08/07/2016
# Última modificación: 07/02/2019

DNSSERVER="servidor"
SINCPUPPET=0
PKGSYNC=0

function print_help {
        echo "$SCRIPT $VERSION"
        echo "Cambiar el nombre del host"
        echo ""
        echo "Uso: $0 [OPTIONS]"
        echo "Opciones reconocidas:"
        echo "  -h               mostrar esta ayuda y salir."
        echo "  -n HOSTNAME      introducir el nombre de host. (sólo se cambiará el hostname si no existe una entrada DNS para este HOST)"
        echo "  -d DNSSERVER     introducir el servidor DNS."
        echo "  -s               ejecutar sinc_puppet."
        echo "  -p               ejecutar pkgsync."
        echo ""
}


##Leer y procesar argumentos
while getopts "n: d: sph" opt
do
    case $opt in
        h ) print_help
            exit ;;
        n ) HOSTNAME=$OPTARG ;;
        d ) DNSSERVER=$OPTARG ;;
        p ) PKGSYNC=1 ;;
        s ) SINCPUPPET=1 ;;
        \? ) echo "Opcion invalida -$OPTARG"
          exit 1 ;;
        : ) echo "Opcion -$OPTARG requiere un argumento"
          exit 1 ;;
    esac
done
shift $((OPTIND-1))

# Si no hay parámetros, el script tratará de obtener el nombre de la máquina consultando al servidor DNSSERVER
if [ -z "$1" ]; then

   INTERFACESUP=$(ip link show up|grep ^[0-9]| grep -v lo|cut -f2 -d":"|sed 's/^[ \t]*//')

   for INTERFACE in $INTERFACESUP; do

      IP=$(ip addr show $INTERFACE | grep -v inet6 | grep 'inet' | sed 's/^[ \t]*//' | cut -f2 -d" " | cut -f1 -d"/")

      if [ "$IP" ]; then
         DOMAINNAME=$(nslookup $IP $DNSSERVER | grep name | sed -e 's/.*[ \t]\([^ \t]*\)\.$/\1/')
         if [ $DOMAINNAME ]; then
            HOSTNAME=${DOMAINNAME%.*}
         fi
      fi
   done

   if [ -z $HOSTNAME ]; then # Si la máquina no está registrada en el servidor DNS, se solicita introducir el nombre por pantalla

      DIALOG="dialog"
      tempfile=`tempfile 2>/dev/null` || tempfile=/tmp/test$$
      trap "rm -f $tempfile" 0 1 2 5 15

      $DIALOG --title "Nombre de host" --clear \
              --inputbox "Introduzca el nombre de host que desea asignar a este equipo. Este nombre debe ser una cadena de caracteres alfanuméricos en minúsculas, sin espacios:" 15 51 2> $tempfile

      retval=$?

      case $retval in
        0)
          NOMBRE=`cat $tempfile`
        ;;
        1) ;;
      esac

   else
      if [ "$HOSTNAME" == "modelo" ]; then
         NOMBRE=`ip -o link  | awk '{print $2,$(NF-2)}' | grep -v -e "lo" -e wl | cut -f2 -d" " | sed 's/://g'`
      else
         NOMBRE=$HOSTNAME
      fi
   fi

else # Se ha introducido el nombre del host como parámetro
   NOMBRE=$1
fi

if [ "$NOMBRE" ] ; then

   echo "127.0.0.1       localhost
127.0.1.1       $NOMBRE

# The following lines are desirable for IPv6 capable hosts
::1     localhost ip6-localhost ip6-loopback
fe00::0 ip6-localnet
ff00::0 ip6-mcastprefix
ff02::1 ip6-allnodes
ff02::2 ip6-allrouters" > /etc/hosts

   echo "$NOMBRE" >  /etc/hostname
   hostname -F /etc/hostname

   echo "Hostname: $NOMBRE"

   [ $SINCPUPPET -eq 1 ] && [ -x /usr/sbin/sinc_puppet ] && /usr/sbin/sinc_puppet -f now
   [ $PKGSYNC -eq 1 ] && [ -x /usr/local/sbin/pkgsync ] && /usr/local/sbin/pkgsync -pcnf

fi
